### ISSUE TITLE
dyld: Library not loaded: @rpath/libreadline.6.2.dylib

### ISSUE THREAD

**Issue by metZaman** [grimmlab/BookChapter-RNA-Seq-Analyses#2]
I am having a problem with running DESeq R code in mac OS.
Could you please advice me?

**Comment by dominikgrimm** [comment]
Our pipeline is developed and test on Ubuntu 18.04.2 LTS. We have not tested the pipeline on MacOS. I am even not sure if all tools we use can be used on Mac. I highly doubt this. 
Nevertheless, if you google the error message it seems to be a problem with your anaconda installation.
